FROM harness/delegate:25.03.85504.minimal
USER root

# Skip curl to avoid conflict
RUN microdnf update -y && microdnf install -y \
    unzip \
    git \
    tar \
    gzip \
    bash \
    java-17-openjdk \
    shadow-utils && \
    microdnf clean all
